name: tezster_dart
description: A flutter package which provides the functionalities to play around
  with tezos dApps
version: 2.1.2-beta.1
homepage: https://github.com/Tezsure/tezster_dart
repository: https://github.com/Tezsure/tezster_dart
issue_tracker: https://github.com/Tezsure/tezster_dart/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.3
  blake2b: ^0.1.2
  bs58check: ^1.0.1
  convert: ^2.1.1
  crypto: ^2.1.5
  flutter_sodium: ^0.1.9
  password_hash: ^2.0.0
  unorm_dart: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
